### PR TITLE
docs: add auto generated docs

### PR DESCRIPTION
**Pull request by MrlolDev**

### CODE REVIEW

**Comment by ZeldaFan0225** [comment]
please provide more information on what this pull request adds/changes/is for as well as why this change is needed/requested

**Comment by MrlolDev** [comment]
Using typedoc I generated new docs for users who want to know what other methods that the package has, Is needed because the actual guide is pretty basic and if you want to know what are the other methods you need to check the types file so this is an easy way.

**Comment by ZeldaFan0225** [comment]
i am not familiar with typedoc so please provide how you generated these docs

**Comment by MrlolDev** [comment]
Typedoc transform the types into markdown documentation where it describes all the methods and properties. It won't affect  anything of your work.

**Comment by MrlolDev** [comment]
You can check it in my  fork: https://github.com/MrlolDev/stable_horde

**Pull request merged**
